"""Local, reproducible research primitives for Anata V2.

The package is intentionally isolated from paper execution. It turns safe,
declarative candidate specs and point-in-time rows into auditable experiment
reports; champion promotion remains an explicit integration concern.
"""

from app.research.evaluation import (
    ChronologicalSplit,
    EvaluationResult,
    PurgedFold,
    PurgedTimeSeriesSplit,
    SignalCorrelation,
    SignalIndependenceAnalysis,
    SignalSeries,
    WalkForwardEvaluator,
    WalkForwardFold,
    WalkForwardResult,
    analyze_signal_independence,
    assess_incremental_contribution,
    assert_point_in_time_availability,
    build_experiment_report,
    calculate_metrics,
    chronological_split,
    evaluate_observations,
    evaluate_predictions,
    observation_from_row,
    transaction_cost_sensitivity,
    write_experiment_report,
)
from app.research.scheduler import (
    CandidateArtifact,
    LabeledDataSnapshot,
    LocalResearchScheduler,
    ResearchRunResult,
    ResearchScheduler,
    ResearchSchedulerConfig,
    ResearchSchedulerState,
    detect_new_labeled_rows,
)
from app.research.schemas import (
    CandidateSearchSpace,
    CandidateStrategySpec,
    DEFAULT_MODEL_FAMILIES,
    EvaluationObservation,
    ExperimentDefinition,
    ExperimentReport,
    ExperimentStatus,
    ResearchValidationError,
    TimeRange,
    ensure_utc,
    parse_window,
    stable_fingerprint,
    stable_json_dumps,
)

__all__ = [
    "CandidateArtifact",
    "CandidateSearchSpace",
    "CandidateStrategySpec",
    "ChronologicalSplit",
    "DEFAULT_MODEL_FAMILIES",
    "EvaluationObservation",
    "EvaluationResult",
    "ExperimentDefinition",
    "ExperimentReport",
    "ExperimentStatus",
    "LabeledDataSnapshot",
    "LocalResearchScheduler",
    "PurgedFold",
    "PurgedTimeSeriesSplit",
    "ResearchRunResult",
    "ResearchScheduler",
    "ResearchSchedulerConfig",
    "ResearchSchedulerState",
    "ResearchValidationError",
    "SignalCorrelation",
    "SignalIndependenceAnalysis",
    "SignalSeries",
    "TimeRange",
    "WalkForwardEvaluator",
    "WalkForwardFold",
    "WalkForwardResult",
    "analyze_signal_independence",
    "assess_incremental_contribution",
    "assert_point_in_time_availability",
    "build_experiment_report",
    "calculate_metrics",
    "chronological_split",
    "detect_new_labeled_rows",
    "ensure_utc",
    "evaluate_observations",
    "evaluate_predictions",
    "observation_from_row",
    "parse_window",
    "stable_fingerprint",
    "stable_json_dumps",
    "transaction_cost_sensitivity",
    "write_experiment_report",
]

